# -*- coding: utf-8 -*-
"""groupingdata_to_analyze.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UH0ib86Jr5Oirk5nlP61UeJqSAGiSfUU """

# Analysing and extracting data to get an insight before starting the complex analysis (csv to dataframe)


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import streamlit as st 

def main():
  st.title("Deploying our data model")
  st.subheader("Our imported data")
  df1=pd.read_csv("urban-and-rural-population.csv")
  st.dataframe(df1)
  
  st.write(df1.describe())
  
  countries=df1['Country'].unique().tolist()
  
  st.subheader("List of available countries")
  st.write(countries)

  inputcountry=st.text_input("Enter the country name: ")

  #creatin a button
  if st.button("apply"):
      display(df1,inputcountry)

def display(df1,inputcountry):
  grouped_by_countries=df1.groupby('Country')
  
  temp_df=grouped_by_countries.get_group(inputcountry)
  st.subheader("Data for {}".format(inputcountry))
  st.write(temp_df)
  
  x=temp_df['Year']
  y=temp_df['Urban_population']
  
  
  plt.bar(x,y)
  plt.xlabel('Year')
  plt.ylabel('Urban_Population')
  fig = plt.gcf()
  fig.set_size_inches(15, 5.5)
  st.pyplot(fig)

if __name__=='__main__':
    main()
